name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
