name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4'

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
